### PR TITLE
Path cannot be other then a string type and should start with a '/' (…

### PR DESCRIPTION
**Pull request by k1ng440**
…Slash).

fix error on \Soundcloud::refreshAccessToken($social->refresh_token)

### CODE REVIEW

**Comment by njasm** [comment]
what does composer have to do with that issue? 

can you provide more info about that issue? it's probably in the core library.. not in this repository.

**Comment by k1ng440** [comment]
@njasm yes the issue on core library. the refreshAccessToken function on 2.x releases seems to be broken.

**Comment by njasm** [comment]
I believe somebody already fixed that issue, it was int `$response = $this->post('/oauth2/token', $finalParams)->asJson() ...`

please update to the latest stable version of the core library with composer.
validate that you have the latest 2.2.4 version and check if the problem persists...
if so, please open a pull/issue in the core lib.

thanks

**Comment by njasm** [comment]
version 2.2.3 have the patch..if i'm not mistaken

**Pull request closed without merging**
