### PR TITLE
Updated the Service Provider & added a Facade

### PR DESCRIPTION
**Pull request by remipelhate**
I noticed you could take this provider a step further, in order to offer some more of the Laravel goodness to your Soundcloud package. I think the updated README should explain it all, but please, don't hesitate to contact me if you've got any questions.

### CODE REVIEW

**Comment by njasm** [comment]
@remipelhate sounds good to me. Can you confirm that everything is working as expected with your changes? If so, I'll merge it. right now I'm at the hospital, my first son has born today and I'll not be able to test anything until next week maybe? :)

**Comment by remipelhate** [comment]
@njasm First of all, congrats man :)!

Actually, these changes come from the Service Provider I'm using for one of my projects. But, just to be sure, I'll pull it in that project in order ensure it works perfectly. I'll let you you as soon as I had the time (busy week).

**Comment by njasm** [comment]
@remipelhate sounds like a plan! thanks man!

**Comment by remipelhate** [comment]
I just tested it in a new Laravel app, works like a charm.

Though, I've been thinking of one last minor improvement: We could add the ability of defining the username and password, enabling to fire the `userCredentials()` automatically when the `SoundcloudFacade` gets registered. I'd do this through a dedicated config file, since it's not part of the authentication process of the API. What do you think?

**Comment by remipelhate** [comment]
Just added that functionality in a separate commit, let me know what you think of it. If it's ok, I'll squash these changes to one commit. If it isn't, I'll revert to the first one.

**Comment by njasm** [comment]
@remipelhate I like the `auto_connect` flag/option. great contribution! Lets merge it. 

Wanna squash the commits first? 

thanks for the contribution :+1:

**Comment by remipelhate** [comment]
@njasm There you, all nicely squashed ;)

**Comment by michellaurent** [comment]
@remipelhate The auto-connect is a a great add-on ! Thanks. 

@njasm Hope this merge request will be soon merged into master and that the package will be tagged as stable.

**Comment by njasm** [comment]
merged! thanks! :+1:

**Pull request merged**
